# Generated by Django 5.1.2 on 2024-11-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutfitShowroom', '0002_outfit_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/'),
        ),
    ]
