# Generated by Django 4.2.16 on 2024-11-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutfitShowroom', '0004_alter_outfit_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/'),
        ),
    ]
